openapi: 3.0.0
info:
  title: Abruzzo API
  description: Flask api for python-java webApp
  version: 0.1.0
servers:
  - url: http://127.0.0.1:5000/
    description: Abruzzo tourism data
paths:
  /abruzzo/:
    get:
      summary: Abruzzo Resources List
      description: Abruzzo Resources List
      responses:
        '200':
          description: A JSON array of object about abruzzo
          content:
            application/json:
              schema:
                type: object
                properties:
                  Region:
                    type: string
                    example: Abruzzo
                  Infrastructure:
                    type: string
                    example: HOTELLIKE
                  ResidenceCountry:
                    type: string
                    example: Italia
                  Date:
                    type: string
                    example: 2008-01-01
                  Arrivals:
                    type: string
                    example: 88624.0
                  Attendance:
                    type: string
                    example: 257703.0